[2023-09-26 06:04:49,717] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 06:04:49,793] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 06:04:49,798] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 06:04:49,800] {taskinstance.py:1357} INFO - Starting attempt 22 of 22
[2023-09-26 06:04:49,801] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 06:04:49,916] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_province_daily> on 2023-09-26 02:58:18.564755+00:00
[2023-09-26 06:04:49,945] {standard_task_runner.py:52} INFO - Started process 2569 to run task
[2023-09-26 06:04:49,951] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_dags', 'get_province_daily', 'manual__2023-09-26T02:58:18.564755+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/1_dags.py', '--cfg-path', '/tmp/tmpw4hqdbfy', '--error-file', '/tmp/tmp10p4xeue']
[2023-09-26 06:04:49,957] {standard_task_runner.py:80} INFO - Job 54: Subtask get_province_daily
[2023-09-26 06:04:50,079] {task_command.py:369} INFO - Running <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [running]> on host 615eeecb9afd
[2023-09-26 06:04:50,281] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dags
AIRFLOW_CTX_TASK_ID=get_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-09-26T02:58:18.564755+00:00
AIRFLOW_CTX_TRY_NUMBER=22
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-26T02:58:18.564755+00:00
[2023-09-26 06:04:50,598] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 538, in cmd_query
    query_attrs=self._query_attrs)
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-08-05' at line 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 271, in execute
    raw_as_string=self._raw_as_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 541, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-08-05' at line 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1_dags.py", line 88, in fun_insert_province_daily
    transformer.transform_daily_province()
  File "/opt/airflow/dags/modules/transformer.py", line 138, in transform_daily_province
    results = conn_mysql.execute("SELECT SUM(covid_jabar."+case+") as a FROM covid_jabar WHERE covid_jabar.tanggal LIKE " + date)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1190, in execute
    future=False,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1491, in _exec_driver_sql
    distilled_parameters,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 271, in execute
    raw_as_string=self._raw_as_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 541, in cmd_query
    sqlstate=exc.sqlstate)
sqlalchemy.exc.ProgrammingError: (***.connector.errors.ProgrammingError) 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-08-05' at line 1
[SQL: SELECT SUM(covid_jabar.closecontact_dikarantina) as a FROM covid_jabar WHERE covid_jabar.tanggal LIKE 2020-08-05]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2023-09-26 06:04:50,810] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_dags, task_id=get_province_daily, execution_date=20230926T025818, start_date=20230926T060449, end_date=20230926T060450
[2023-09-26 06:04:50,864] {standard_task_runner.py:97} ERROR - Failed to execute job 54 for task get_province_daily ((***.connector.errors.ProgrammingError) 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-08-05' at line 1
[SQL: SELECT SUM(covid_jabar.closecontact_dikarantina) as a FROM covid_jabar WHERE covid_jabar.tanggal LIKE 2020-08-05]
(Background on this error at: http://sqlalche.me/e/14/f405); 2569)
[2023-09-26 06:04:50,930] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-26 06:04:51,127] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
