[2023-09-26 05:53:24,760] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 05:53:24,775] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 05:53:24,775] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 05:53:24,776] {taskinstance.py:1357} INFO - Starting attempt 15 of 15
[2023-09-26 05:53:24,776] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 05:53:24,843] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_province_daily> on 2023-09-26 02:58:18.564755+00:00
[2023-09-26 05:53:24,859] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_dags', 'get_province_daily', 'manual__2023-09-26T02:58:18.564755+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/1_dags.py', '--cfg-path', '/tmp/tmp8gf5ilv5', '--error-file', '/tmp/tmpbp1tl9wa']
[2023-09-26 05:53:24,857] {standard_task_runner.py:52} INFO - Started process 2416 to run task
[2023-09-26 05:53:24,861] {standard_task_runner.py:80} INFO - Job 47: Subtask get_province_daily
[2023-09-26 05:53:24,982] {task_command.py:369} INFO - Running <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [running]> on host 615eeecb9afd
[2023-09-26 05:53:25,122] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dags
AIRFLOW_CTX_TASK_ID=get_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-09-26T02:58:18.564755+00:00
AIRFLOW_CTX_TRY_NUMBER=15
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-26T02:58:18.564755+00:00
[2023-09-26 05:53:25,509] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1_dags.py", line 88, in fun_insert_province_daily
    transformer.transform_daily_province()
  File "/opt/airflow/dags/modules/transformer.py", line 140, in transform_daily_province
    total=results['pisang'])
TypeError: 'LegacyCursorResult' object is not subscriptable
[2023-09-26 05:53:25,530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_dags, task_id=get_province_daily, execution_date=20230926T025818, start_date=20230926T055324, end_date=20230926T055325
[2023-09-26 05:53:25,544] {standard_task_runner.py:97} ERROR - Failed to execute job 47 for task get_province_daily ('LegacyCursorResult' object is not subscriptable; 2416)
[2023-09-26 05:53:25,561] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-26 05:53:25,589] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
