[2023-09-26 05:19:30,020] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 05:19:30,028] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 05:19:30,029] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 05:19:30,030] {taskinstance.py:1357} INFO - Starting attempt 7 of 7
[2023-09-26 05:19:30,030] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 05:19:30,044] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_province_daily> on 2023-09-26 02:58:18.564755+00:00
[2023-09-26 05:19:30,050] {standard_task_runner.py:52} INFO - Started process 1996 to run task
[2023-09-26 05:19:30,053] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_dags', 'get_province_daily', 'manual__2023-09-26T02:58:18.564755+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/1_dags.py', '--cfg-path', '/tmp/tmpxglt1wzk', '--error-file', '/tmp/tmpr8798stl']
[2023-09-26 05:19:30,054] {standard_task_runner.py:80} INFO - Job 39: Subtask get_province_daily
[2023-09-26 05:19:30,111] {task_command.py:369} INFO - Running <TaskInstance: 1_dags.get_province_daily manual__2023-09-26T02:58:18.564755+00:00 [running]> on host 615eeecb9afd
[2023-09-26 05:19:30,183] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dags
AIRFLOW_CTX_TASK_ID=get_province_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-09-26T02:58:18.564755+00:00
AIRFLOW_CTX_TRY_NUMBER=7
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-26T02:58:18.564755+00:00
[2023-09-26 05:19:30,309] {transformer.py:139} INFO - <sqlalchemy.engine.cursor.LegacyCursorResult object at 0x7f7ac0847450>
[2023-09-26 05:19:30,328] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x7f7ac0847450>"
LINE 1: ...e_id, date, total) VALUES ('32', 1, '2020-08-05', '<sqlalche...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1_dags.py", line 88, in fun_insert_province_daily
    transformer.transform_daily_province()
  File "/opt/airflow/dags/modules/transformer.py", line 145, in transform_daily_province
    session.commit()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1423, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3255, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3395, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 3355, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 453, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    uow,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 247, in save_obj
    insert,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1222, in _emit_insert_statements
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1399, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 716, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x7f7ac0847450>"
LINE 1: ...e_id, date, total) VALUES ('32', 1, '2020-08-05', '<sqlalche...
                                                             ^

[SQL: INSERT INTO province_daily (province_id, case_id, date, total) VALUES (%(province_id)s, %(case_id)s, %(date)s, %(total)s) RETURNING province_daily.id]
[parameters: {'province_id': '32', 'case_id': 1, 'date': '2020-08-05', 'total': '<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x7f7ac0847450>'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h)
[2023-09-26 05:19:30,354] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_dags, task_id=get_province_daily, execution_date=20230926T025818, start_date=20230926T051930, end_date=20230926T051930
[2023-09-26 05:19:30,365] {standard_task_runner.py:97} ERROR - Failed to execute job 39 for task get_province_daily ((psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x7f7ac0847450>"
LINE 1: ...e_id, date, total) VALUES ('32', 1, '2020-08-05', '<sqlalche...
                                                             ^

[SQL: INSERT INTO province_daily (province_id, case_id, date, total) VALUES (%(province_id)s, %(case_id)s, %(date)s, %(total)s) RETURNING province_daily.id]
[parameters: {'province_id': '32', 'case_id': 1, 'date': '2020-08-05', 'total': '<sqlalchemy.engine.cursor.LegacyCursorResult object at 0x7f7ac0847450>'}]
(Background on this error at: http://sqlalche.me/e/14/9h9h); 1996)
[2023-09-26 05:19:30,386] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-26 05:19:30,415] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
