[2023-09-26 04:29:50,099] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:29:50,109] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:29:50,110] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:29:50,110] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-09-26 04:29:50,110] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:29:50,126] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_district_daily> on 2023-09-26 02:58:18.564755+00:00
[2023-09-26 04:29:50,135] {standard_task_runner.py:52} INFO - Started process 1384 to run task
[2023-09-26 04:29:50,136] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_dags', 'get_district_daily', 'manual__2023-09-26T02:58:18.564755+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/1_dags.py', '--cfg-path', '/tmp/tmpvt6xqw69', '--error-file', '/tmp/tmpe9t9jwtx']
[2023-09-26 04:29:50,138] {standard_task_runner.py:80} INFO - Job 29: Subtask get_district_daily
[2023-09-26 04:29:50,254] {task_command.py:369} INFO - Running <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [running]> on host 615eeecb9afd
[2023-09-26 04:29:50,332] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dags
AIRFLOW_CTX_TASK_ID=get_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-09-26T02:58:18.564755+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-26T02:58:18.564755+00:00
[2023-09-26 04:29:50,538] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1_dags.py", line 111, in fun_insert_district_daily
    transformer.transform_daily_district()
  File "/opt/airflow/dags/modules/transformer.py", line 108, in transform_daily_district
    Session = sessionmaker(bind=db_postgre)
NameError: name 'db_postgre' is not defined
[2023-09-26 04:29:50,563] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_dags, task_id=get_district_daily, execution_date=20230926T025818, start_date=20230926T042950, end_date=20230926T042950
[2023-09-26 04:29:50,578] {standard_task_runner.py:97} ERROR - Failed to execute job 29 for task get_district_daily (name 'db_postgre' is not defined; 1384)
[2023-09-26 04:29:50,595] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-26 04:29:50,635] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
