[2023-09-26 04:37:38,271] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:37:38,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:37:38,281] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:37:38,281] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2023-09-26 04:37:38,282] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:37:38,299] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_district_daily> on 2023-09-26 02:58:18.564755+00:00
[2023-09-26 04:37:38,306] {standard_task_runner.py:52} INFO - Started process 1480 to run task
[2023-09-26 04:37:38,332] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_dags', 'get_district_daily', 'manual__2023-09-26T02:58:18.564755+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/1_dags.py', '--cfg-path', '/tmp/tmpkwz6oegj', '--error-file', '/tmp/tmprwaoh0ux']
[2023-09-26 04:37:38,333] {standard_task_runner.py:80} INFO - Job 31: Subtask get_district_daily
[2023-09-26 04:37:38,462] {task_command.py:369} INFO - Running <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [running]> on host 615eeecb9afd
[2023-09-26 04:37:38,613] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dags
AIRFLOW_CTX_TASK_ID=get_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-09-26T02:58:18.564755+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-26T02:58:18.564755+00:00
[2023-09-26 04:37:39,036] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1_dags.py", line 111, in fun_insert_district_daily
    transformer.transform_daily_district()
  File "/opt/airflow/dags/modules/transformer.py", line 115, in transform_daily_district
    new_case = District_Daily(district_id=row['kode_kab'],case_id=list_cas_id[case.index], date=row['tanggal'], total=row[case])
TypeError: list indices must be integers or slices, not builtin_function_or_method
[2023-09-26 04:37:39,149] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_dags, task_id=get_district_daily, execution_date=20230926T025818, start_date=20230926T043738, end_date=20230926T043739
[2023-09-26 04:37:39,166] {standard_task_runner.py:97} ERROR - Failed to execute job 31 for task get_district_daily (list indices must be integers or slices, not builtin_function_or_method; 1480)
[2023-09-26 04:37:39,208] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-26 04:37:39,238] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
