[2023-09-26 04:39:27,292] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:39:27,301] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [queued]>
[2023-09-26 04:39:27,301] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:39:27,302] {taskinstance.py:1357} INFO - Starting attempt 5 of 5
[2023-09-26 04:39:27,302] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-26 04:39:27,316] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_district_daily> on 2023-09-26 02:58:18.564755+00:00
[2023-09-26 04:39:27,322] {standard_task_runner.py:52} INFO - Started process 1507 to run task
[2023-09-26 04:39:27,325] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_dags', 'get_district_daily', 'manual__2023-09-26T02:58:18.564755+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/1_dags.py', '--cfg-path', '/tmp/tmpq8c9jh3n', '--error-file', '/tmp/tmpl_a2fvlx']
[2023-09-26 04:39:27,326] {standard_task_runner.py:80} INFO - Job 32: Subtask get_district_daily
[2023-09-26 04:39:27,387] {task_command.py:369} INFO - Running <TaskInstance: 1_dags.get_district_daily manual__2023-09-26T02:58:18.564755+00:00 [running]> on host 615eeecb9afd
[2023-09-26 04:39:27,455] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dags
AIRFLOW_CTX_TASK_ID=get_district_daily
AIRFLOW_CTX_EXECUTION_DATE=2023-09-26T02:58:18.564755+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-26T02:58:18.564755+00:00
[2023-09-26 04:39:27,683] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/1_dags.py", line 111, in fun_insert_district_daily
    transformer.transform_daily_district()
  File "/opt/airflow/dags/modules/transformer.py", line 115, in transform_daily_district
    new_case = District_Daily(district_id=row['kode_kab'],case_id=list_cas_id[case.index()], date=row['tanggal'], total=row[case])
TypeError: index() takes at least 1 argument (0 given)
[2023-09-26 04:39:27,714] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=1_dags, task_id=get_district_daily, execution_date=20230926T025818, start_date=20230926T043927, end_date=20230926T043927
[2023-09-26 04:39:27,737] {standard_task_runner.py:97} ERROR - Failed to execute job 32 for task get_district_daily (index() takes at least 1 argument (0 given); 1507)
[2023-09-26 04:39:27,779] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-26 04:39:27,831] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
